/**
 * @file art.c
 * @brief Pre-composed 20x5 scene illustrations (see art.h) and the
 *        blitter that draws one at the top of the screen.
 */
#include "art.h"
#include "sprite16.h"

/* BG_VILLAGE: night village, moon, house cluster */
static const uint8_t bg_village[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_MOON,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_HOUSE_WALL,T_HOUSE_WALL,T_DOOR,T_HOUSE_WALL,T_HOUSE_WALL,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
    {T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH},
};

/* BG_SWAMP: misty marsh, dead trees, water */
static const uint8_t bg_swamp[BG_ROWS][BG_COLS] = {
    {T_SKY,T_SKY,T_SKY,T_SKY,T_MOON,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY},
    {T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG},
    {T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER},
    {T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER},
    {T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER},
};

/* BG_RUIN: watchtower exterior at night */
static const uint8_t bg_ruin[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_MOON,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_WALL,T_WALL,T_DOOR,T_WALL,T_WALL,T_WALL,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
    {T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH},
};

/* BG_RUIN_INSIDE: torch-lit corridor */
static const uint8_t bg_ruin_inside[BG_ROWS][BG_COLS] = {
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
};

/* BG_RUIN_CHAMBER: upper room with chest */
static const uint8_t bg_ruin_chamber[BG_ROWS][BG_COLS] = {
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL},
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_CHEST,T_CHEST,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
};

/* BG_RUIN_TOP_FIGHT: crumbling top chamber, monster */
static const uint8_t bg_ruin_top_fight[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL},
    {T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL},
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_MONSTER,T_MONSTER,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
};

/* BG_RUIN_TOP_WON: crumbling top chamber, crown */
static const uint8_t bg_ruin_top_won[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL,T_WALL,T_SKY_STAR,T_WALL},
    {T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL_TORCH,T_WALL,T_WALL},
    {T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_CROWN,T_CROWN,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL,T_WALL},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
    {T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR,T_FLOOR},
};

/* BG_DEATH: swallowed by mist */
static const uint8_t bg_death[BG_ROWS][BG_COLS] = {
    {T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY},
    {T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG},
    {T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG},
    {T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG},
    {T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG,T_FOG},
};

static const uint8_t (*const bg_table[BG_COUNT])[BG_COLS] = {
    [BG_VILLAGE]        = bg_village,
    [BG_SWAMP]           = bg_swamp,
    [BG_RUIN]            = bg_ruin,
    [BG_RUIN_INSIDE]     = bg_ruin_inside,
    [BG_RUIN_CHAMBER]    = bg_ruin_chamber,
    [BG_RUIN_TOP_FIGHT]  = bg_ruin_top_fight,
    [BG_RUIN_TOP_WON]    = bg_ruin_top_won,
    [BG_DEATH]           = bg_death,
};

/** @brief See draw_scene_bg() in the header for the full contract. */
void draw_scene_bg(bg_id_t bg)
{
    const uint8_t (*grid)[BG_COLS] = bg_table[bg];

    for (int row = 0; row < BG_ROWS; row++)
        for (int col = 0; col < BG_COLS; col++)
            draw_sprite16(col * 16, row * 16, &tileset16[grid[row][col]]);
}
