/**
 * @file art.c
 * @brief Pre-composed 20x5 scene illustrations (see art.h) and the
 *        blitter that draws one at the top of the screen.
 */
#include "art.h"
#include "sprite16.h"

/* BG_WALD: dense, featureless forest - the default for a forest cell
 * with no station on it */
static const uint8_t bg_wald[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
};

/* BG_HAUS: an overgrown old house between the trees */
static const uint8_t bg_haus[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_MOON,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_ROOF,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_HOUSE_WALL,T_HOUSE_WALL,T_HOUSE_WALL,T_DOOR,T_HOUSE_WALL,T_HOUSE_WALL,T_HOUSE_WALL,T_HOUSE_WALL,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_TREE,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_TREE},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
};

/* BG_KOBOLD: a small clearing, the kobold sitting in the middle
 * (reuses T_MONSTER - a small green creature, fits as-is) */
static const uint8_t bg_kobold[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_MONSTER,T_MONSTER,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
};

/* BG_MOOR: boggy wetland, dead trees, fog */
static const uint8_t bg_moor[BG_ROWS][BG_COLS] = {
    {T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY,T_SKY},
    {T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG,T_SKY,T_FOG,T_FOG,T_FOG},
    {T_WATER,T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER,T_TREE,T_WATER,T_WATER,T_WATER},
    {T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER},
    {T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER,T_WATER},
};

/* BG_BACH: a clear stream crossing a forest clearing */
static const uint8_t bg_bach[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_WATER,T_WATER,T_WATER,T_WATER,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_WATER,T_WATER,T_WATER,T_WATER,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_WATER,T_WATER,T_WATER,T_WATER,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
};

/* BG_PFAD: the path leading up to the forest's edge */
static const uint8_t bg_pfad[BG_ROWS][BG_COLS] = {
    {T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR,T_SKY_STAR},
    {T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE,T_TREE,T_TREE,T_SKY_STAR,T_TREE},
    {T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE,T_TREE},
    {T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND,T_GROUND},
    {T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH,T_PATH},
};

static const uint8_t (*const bg_table[BG_COUNT])[BG_COLS] = {
    [BG_WALD]   = bg_wald,
    [BG_HAUS]   = bg_haus,
    [BG_KOBOLD] = bg_kobold,
    [BG_MOOR]   = bg_moor,
    [BG_BACH]   = bg_bach,
    [BG_PFAD]   = bg_pfad,
};

/** @brief See draw_scene_bg() in the header for the full contract. */
void draw_scene_bg(bg_id_t bg)
{
    const uint8_t (*grid)[BG_COLS] = bg_table[bg];

    for (int row = 0; row < BG_ROWS; row++)
        for (int col = 0; col < BG_COLS; col++)
            draw_sprite16(col * 16, row * 16, &tileset16[grid[row][col]]);
}
