/**
 * @file music.h
 * @brief Tiny sequencer that plays a MusicNote[] track through sfx.h's
 *        voice 0 (sfx_play_freq()). Games supply their own track data
 *        (see examples/dig-demo/track.h for an example generated by
 *        tools/midi2console.py).
 */
#pragma once
#include <stdint.h>

/**
 * @brief One note in a music track: a frequency held for a duration.
 */
typedef struct {
    uint16_t freq;     /**< Frequency in Hz, or 0 for a rest/pause. */
    uint16_t duration; /**< Duration in ms. A duration of 0 marks the
                         *   end of the track (loops back to the start). */
} MusicNote;

/**
 * @brief Starts playing a track from its first note. The track data
 *        must outlive playback (it is not copied) and must be
 *        NULL/0-duration terminated.
 * @param track Note sequence to play.
 */
void music_init(const MusicNote *track);

/**
 * @brief Starts an optional second "bass" voice alongside music_init()'s
 *        melody, playing its own note sequence on the engine's third SID
 *        voice (see sfx_play_bass_freq()). Call once after music_init();
 *        games that skip this play melody-only, as before. The melody
 *        and bass channels loop independently on their own note
 *        sequences, so for a bass line that stays in phase with the
 *        melody across loops, its total duration (the sum of all
 *        durations before the terminator) should match the melody
 *        track's total duration.
 * @param track Bass note sequence; same format as music_init()'s track,
 *              NULL/0-duration terminated. Not copied, must outlive
 *              playback.
 */
void music_init_bass(const MusicNote *track);

/**
 * @brief Advances playback by one millisecond. Call once per ms (in this
 *        project, from sfx.c's internal 1 ms tick).
 */
void music_update_1ms(void);

/** @brief Stops playback (melody and bass, if started) and silences
 *         both voices. */
void music_stop(void);
