/**
 * @file music.h
 * @brief Tiny sequencer that plays a MusicNote[] track through sfx.h's
 *        voice 0 (sfx_play_freq()). Games supply their own track data
 *        (see examples/dig-demo/track.h for an example generated by
 *        tools/midi2console.py).
 */
#pragma once
#include <stdint.h>

/**
 * @brief One note in a music track: a frequency held for a duration.
 */
typedef struct {
    uint16_t freq;     /**< Frequency in Hz, or 0 for a rest/pause. */
    uint16_t duration; /**< Duration in ms. A duration of 0 marks the
                         *   end of the track (loops back to the start). */
} MusicNote;

/**
 * @brief Starts playing a track from its first note. The track data
 *        must outlive playback (it is not copied) and must be
 *        NULL/0-duration terminated.
 * @param track Note sequence to play.
 */
void music_init(const MusicNote *track);

/**
 * @brief Advances playback by one millisecond. Call once per ms (in this
 *        project, from sfx.c's internal 1 ms tick).
 */
void music_update_1ms(void);

/** @brief Stops playback and silences the music voice. */
void music_stop(void);
